services:
    englishtutorai.api:
        image: englishtutorai.api
        container_name: englishtutorai.api
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        image: postgres:latest
        container_name: englishtutorai.database
        env_file:
            - docker-variables.env
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data: