services:
    englishtutorai.api:
        image: englishtutorai.api
        container_name: englishtutorai.api
        build:
            context: .
            dockerfile: EnglishTutorAI.Api/Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        image: postgres:16
        container_name: englishtutorai.database
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data: