name: CI Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: ["dev"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Run Containers
      run: |
        docker compose -f server/docker-compose.yml build
        docker compose -f server/docker-compose.yml up -d

    - name: Push API Image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/englishtutorai.api:latest ${{ secrets.DOCKER_USERNAME }}/englishtutorai.api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/englishtutorai.api:latest

  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
              cd EnglishTutorAI/server
              echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
              docker-compose down --volumes --remove-orphans
              docker-compose pull
              docker-compose up -d --build