name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Run Containers
      run: |
        docker-compose -f server/docker-compose.yml build
        docker-compose -f server/docker-compose.yml up -d

    - name: Push API Image
      run: |
        docker tag englishtutorai.api:latest ${{ secrets.DOCKER_USERNAME }}/englishtutorai.api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/englishtutorai.api:latest